# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  # Define conda-forge packages here -> https://anaconda.org/search
  # When available, prefer the conda-forge packages over pip as installations are more efficient.
  - python=3.9.13 # https://pyreadiness.org/3.9/
  - qt=5.12.9
  - pyqt=5.12.3
  - pip=22.1.2 # https://pip.pypa.io/en/stable/news/
  - pip:
      # Define pip packages here -> https://pypi.org/
      - pywebview[qt]==3.6.3
      - rpaframework==19.4.1 # https://rpaframework.org/releasenotes.html
