name: Upload to Control Room

on: [push]
      
jobs:
  upload-to-control-room:
    runs-on: ubuntu-latest
    name: Upload to Control Room   
    steps:
      - name: Checkout files from repositor
      - uses: actions/checkout@v2
      - name: Upload robot to Control Room
        uses: robocorp/action-upload-robot@v1
        with:
          workspace-key: ${{ secrets.ROBOCORP_WORKSPACE_KEY }}
          workspace-id: ${{ secrets.ROBOCORP_WORKSPACE_ID }}
          robot-id: ${{ secrets.ROBOCORP_ROBOT_ID }}
    
